In [1]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할 때 사용하는 자료구조
# 스칼라(0차원 텐서) - 단일 데이터
# 벡터(1차원 텐서) : 리스트 형태 [1, 2, 3, 4]
# 행렬 (2차원 텐서) : 행과 열로 이루어진 데이터 표데이터, 흑백 이미지
# (3차원 텐서) : 컬러 이미지, 흑백이미지 + 채널정보 (R G B) 
# 고차원텐서 : 동영상, 이미지개수 X 가로픽셀 X 세로픽셀 X 채널정보

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병렬연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [3]:
%pip install torch  torchvision

Note: you may need to restart the kernel to use updated packages.


In [2]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
# 랜덤 텐서
torch.rand(3,4)

tensor([[0.2071, 0.0623, 0.9565, 0.1126],
        [0.8994, 0.3011, 0.1284, 0.4706],
        [0.2240, 0.4634, 0.9002, 0.8848]])

In [6]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
# 1로 채워진 텐서
torch.ones(3,4,dtype=torch.long)

tensor([1., 1., 1.])

In [8]:
import numpy as np

In [ ]:
# 토치와 넘파이와 출력 형식 비교

torch.tensor([3.5,3,2.1])
np.array([3.5,3,2.1])


array([3.5, 3. , 2.1])

In [10]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x, dtype=torch.float)
x, y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[-0.7674,  0.8203,  1.9121, -0.7247],
         [-0.1061, -2.4972, -0.8974,  1.4369],
         [ 1.2825,  0.4118, -1.2786,  0.1976]]))

In [11]:
# 덧셈

import torch
x=torch.rand(3,4)
y=torch.rand(3,4)

x,y, x+y

(tensor([[0.2445, 0.7993, 0.4054, 0.3959],
         [0.2072, 0.1102, 0.7913, 0.7185],
         [0.0304, 0.4948, 0.4266, 0.8702]]),
 tensor([[0.3851, 0.7097, 0.3283, 0.1217],
         [0.6472, 0.7246, 0.9396, 0.1053],
         [0.8134, 0.2055, 0.3147, 0.1432]]),
 tensor([[0.6295, 1.5090, 0.7337, 0.5175],
         [0.8544, 0.8348, 1.7309, 0.8239],
         [0.8438, 0.7003, 0.7413, 1.0134]]))

In [12]:
# 덧셈 함수로도 가능
torch.add(x,y)

tensor([[0.6295, 1.5090, 0.7337, 0.5175],
        [0.8544, 0.8348, 1.7309, 0.8239],
        [0.8438, 0.7003, 0.7413, 1.0134]])

In [13]:
# in-place y = y + x    y += x
y.add_(x)

tensor([[0.6295, 1.5090, 0.7337, 0.5175],
        [0.8544, 0.8348, 1.7309, 0.8239],
        [0.8438, 0.7003, 0.7413, 1.0134]])

In [14]:
# 행렬의 곱셉
x=torch.rand(3,4)
y=torch.rand(4,5)
x,y, torch.mm(x,y),x@y   # 파이썬 3.5부터 x@y 로도 표현 가능  # 다른차원의 곱셉은 (3,4) (4,5) --> 3x5


(tensor([[0.8789, 0.1202, 0.7582, 0.0641],
         [0.7866, 0.0862, 0.8859, 0.2963],
         [0.9622, 0.2730, 0.2760, 0.7717]]),
 tensor([[0.8764, 0.2410, 0.1000, 0.1087, 0.9015],
         [0.5523, 0.7982, 0.5530, 0.2930, 0.2929],
         [0.7572, 0.4024, 0.4129, 0.4574, 0.0666],
         [0.3375, 0.4961, 0.6295, 0.3397, 0.8224]]),
 tensor([[1.4324, 0.6446, 0.5077, 0.4993, 0.9308],
         [1.5078, 0.7618, 0.6787, 0.6166, 1.0371],
         [1.4635, 0.9437, 0.8470, 0.5729, 1.6005]]),
 tensor([[1.4324, 0.6446, 0.5077, 0.4993, 0.9308],
         [1.5078, 0.7618, 0.6787, 0.6166, 1.0371],
         [1.4635, 0.9437, 0.8470, 0.5729, 1.6005]]))

In [15]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
x*y

tensor([1, 4, 9])

In [16]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[0,2:]
x[1,1], x[1,1].item() ,type(x[1,1]), type(x[1,1].item())

(tensor(0.8195), 0.8194689154624939, torch.Tensor, float)

In [17]:
# 텐서 모양 변경  view => reshape 
# 텐서 모양 확인  size -> shape  
# 가독성 --- view size 사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시

In [18]:
# 텐서 크기 변경 reshape,view    numpy동일한 기능 reshape
import torch
x = torch.rand(4,4)
y = x.view(-1)      # -1은 자동계산
x,y,x.shape,y.shape

(tensor([[0.0143, 0.9835, 0.9971, 0.9217],
         [0.9702, 0.3167, 0.8437, 0.5553],
         [0.2086, 0.3359, 0.9231, 0.6352],
         [0.8773, 0.4749, 0.9489, 0.4761]]),
 tensor([0.0143, 0.9835, 0.9971, 0.9217, 0.9702, 0.3167, 0.8437, 0.5553, 0.2086,
         0.3359, 0.9231, 0.6352, 0.8773, 0.4749, 0.9489, 0.4761]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [19]:
# x는 4x4
x.view(2,8)
x.view(-1,8)            # -1 자동계산
x.view(2,-1)

tensor([[0.0143, 0.9835, 0.9971, 0.9217, 0.9702, 0.3167, 0.8437, 0.5553],
        [0.2086, 0.3359, 0.9231, 0.6352, 0.8773, 0.4749, 0.9489, 0.4761]])

In [20]:
x.size

<function Tensor.size>

In [ ]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
# np.array(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
# 넘파이 -> 텐서

a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [15]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda')  # cuda는 GPU
    # 텐서들은 GPU에서 연산해야되기 떄문에 생성을 GPU에서 생성
    x = torch.ones(5, device=device)        # gpu에서 생성
    y = torch.ones(5)                       # cpu에서 생성
    y = y.to(device)                        # cpu -> gpu로 생성
    z = x +y
    print(f'GPU 생성결과: {z}')
    print(f'다시 CPU로 : {z.to("cpu",torch.double)} ')
else:
    print('CUDA를 사용할 수 없습니다')
    device = torch.device('cpu')


CUDA를 사용할 수 없습니다


In [ ]:
# 행렬의 곱셈 공식
# (x, y)  * (x1, y1)
# y와 x1의 차수는 같아야 한다 (2,4) (2,10)


# 행렬곱의 결과는 x, y1     (2,10)

# 텐서는 딥러닝을 위해 만든 자료구조, 내부에 gpu 연산에 특화된 구조 일반적인 모양은 넘파이와 동일
# 텐서는 gpu 연산을 지원한다

In [ ]:
# 자동미분(Autograd) 매 계산 과정마다 해당 계산과정의 미분값을 저장
# 파이토치 required_grad = True 로 설정하면 계산그래프라는 형태로 기록 - 동영상 녹화와 비슷한 원리
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다

In [6]:
x = torch.ones(2,2, requires_grad=True)
x,  x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [ ]:
y = x + 2   # y도 계산 그래프에 추가
print(y, y.grad_fn)     # grad_fn = gradient function
z = y*y*3               # z=3(x+2)**2 와 같은 의미
out = z.mean()          # backwoard()는 스칼라값(1개의 숫자)일때만 자동으로 미분을 계산할 수 있기 떄문에, 손실함수의 평균을 내서 하나의 값으로 만들어주는 것
z, out

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x0000029F4C3E0100>


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [ ]:
# 기울기 구하는 과정을   역전파 -> 기울기 계산
# 최종결과가 out에서부터 시작해서 계산그래프를 거꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분
out.backward()
x.grad

In [ ]:
# out = 1/4(z1+z2+z3+z4)
# z + 3y^2
# y = x +2

# d-out/dxi = 

In [ ]:
# 기울기 제어
# 역전파, torch.no_grad, detech
# requied_grad =    True 연산추적
import torch
x = torch.randn(3, requires_grad=True)
print(x)
# y는 x로부터 연산기록을 물려받음
y = x * 2
print(y)   
# 유클리드 노름 : 벡터의 크기를 측정하는 방법(원점으로부터 벡터까지의 거리)/ 모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근(루트)를 씌운다
y.data.norm() 
# y의 실제데이터의 크기를 확인해서 반복
i = 0
while y.data.norm() <1000 :
    y = y*2
    i += 1
print(f'y:{y}')
print(f'반복횟수 : {i}')

# 벡터에 대한 역전파(야코비안 행렬)
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안 - 벡토의 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v) # Y를 X에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터 V를 곱하라는 의미
# Vt*j
print(f'x.grad : {x.grad}')




tensor([0.4401, 2.0569, 0.7041], requires_grad=True)
tensor([0.8801, 4.1139, 1.4082], grad_fn=<MulBackward0>)
y:tensor([ 225.3133, 1053.1520,  360.5077], grad_fn=<MulBackward0>)
반복횟수 : 8
x.grad : tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


스칼라 백워드 Scalar Backward : 역전파로 구하는 기울기가 하나일 때
out.backward() 
최종점수가 숫자하나  ex) 수학공부 1시간 했을 때 최종저수에 몇점의 영향을 줬는지
최종 목표가 하나 (스칼라) 이기 때문에 각 원인(각 변수)의 기여도를 바로 게산할 수 있음

벡터 백워드 Vector Backward : 기울기가 여러개 일때
y.backward(v)
과목별 점수가 담긴 성적표(벡터) 공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함. 과목이 여러개이기 때문에
가중치 또는 중요도를 알려주는 벡터가 필요  (v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인

In [12]:
x.requires_grad

True

In [14]:
# 각 학습을 진행하면서 도중에 모델의 성능 평가가 필요 - 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부 : {(x**2).requires_grad}')

# .detach() 계산그래프에서 텐서를 분리
print(f'detach 전 {y.requires_grad}')
y = x.detach()
print(f'detach 후  {y.requires_grad}')

no_grad 내부 : False
detach 전 True
detach 후  False
